import React from 'react'
import NavbarTop from '../../navbarTop/NavbarTop'
import "./Terms.css"
import {Link} from "react-router-dom"
import Footer from '../../Footer/Footer'

function Terms() {
  return (
    <div className="TermsContainer">
 <NavbarTop/>
  <div className="pagesNavigation"><Link to="/">Home</Link> {'>'} <Link to="/terms">Terms & Conditions</Link>  </div>    
  
<h1>Terms & Conditions</h1>
<h2>1. Definitions</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

Morbi eu sapien nec felis tempor iaculis quis quis lacus. Phasellus et purus vel tellus congue finibus. Ut id volutpat orci, at lobortis libero. Vestibulum lacinia augue scelerisque, vehicula est sed, scelerisque ante. Suspendisse semper dignissim scelerisque. Praesent sagittis nisi et luctu
<h2>2. Description of Olympi Services</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>3. Quality, Maintenance and Accessibility</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>4. Intellectual Property</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>5. Permissible Use Policy</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>6. Pricing & Invoicing</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>7. Confidentiality</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>8. Information Security and Privacy</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>9. Warranty</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>10. Indemnification</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>11. Limitations of Liability</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>12. Term, Suspension and Termination</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>13.  Governing Law</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>14. Force Majeure</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>15. Notices</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>16. Amendments</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.

<h2>17. General Provisions</h2>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat sapien. Suspendisse potenti. Vestibulum mattis, mauris id convallis auctor, dolor justo dapibus odio, ut placerat justo lacus viverra sem. Ut at cursus lorem, vitae egestas quam. Praesent tempus, orci eget interdum aliquet, est sapien pretium lorem, id dapibus ipsum purus eget tellus. Aenean lorem nulla, auctor non condimentum ac, scelerisque sed metus. Nam luctus mollis ex, in efficitur nisl porta ac. Sed magna nisi, efficitur et gravida sed, eleifend eu nisi. Sed posuere, elit quis cursus rhoncus, quam velit consequat purus, id laoreet ante mauris ac ante. Aliquam imperdiet, velit tempus mollis rutrum, massa est volutpat justo, vitae finibus mauris metus id arcu. Nunc commodo dapibus accumsan. Maecenas nec accumsan tellus. Quisque vitae tortor laoreet, hendrerit ante eget, rhoncus nisl. Nam eleifend tortor non rhoncus lobortis. Maecenas sed auctor nulla.


     <Footer/>
    </div>
    
  )
}

export default Terms
